/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { styled } from '@mui/material/styles';
import Reaction from 'components/Reaction/Reaction';
import { FeedbackBarProps } from 'types';

 
const FeedbackBar1: any = styled("div")({  
  background: `linear-gradient(89.35deg, rgba(83, 178, 246, 1) 9.171226722085123%, rgba(124, 98, 255, 1) 90.7781752159856%)`,  
  border: `1px solid rgba(176, 176, 176, 0.5)`,  
  boxSizing: `border-box`,  
  borderRadius: `8px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  width: "100%",  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `28px 38px 38px 38px`,  
});
  
const FeedbackText: any = styled("div")(({ theme }: any) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: theme.palette["Primary"]["Contrast"],  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `600`,  
  fontSize: `24px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  margin: `0px`,  
}));
  
const Btm: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `20px 0px 0px 0px`,  
});
  
const Frame3: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const Reaction1: any = styled(Reaction)(({ theme }: any) =>({  
  width: `221px`,  
  height: `42px`,  
}));
  
const Reaction2: any = styled(Reaction)(({ theme }: any) =>({  
  width: `221px`,  
  height: `42px`,  
}));
  
const Reaction3: any = styled(Reaction)(({ theme }: any) =>({  
  width: `221px`,  
  height: `42px`,  
}));
  
const Reaction4: any = styled(Reaction)(({ theme }: any) =>({  
  width: `221px`,  
  height: `42px`,  
}));
 
function FeedbackBar(props: FeedbackBarProps): JSX.Element {
  return (
    <FeedbackBar1 className={props.className} >
      <FeedbackText >
        {`How are you feeling today?`}
          </FeedbackText>
      <Btm >
        <Frame3 >
          <Reaction1   />
          <Reaction2   />
          <Reaction3   />
          <Reaction4   />
        </Frame3>
      </Btm>
    </FeedbackBar1>
  );
}

export default FeedbackBar;
