/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { styled } from '@mui/material/styles';
import SidebarRow from 'components/SidebarRow/SidebarRow';
import { SidebarProps } from 'types';

 
const CollapsableOpen: any = styled("div")({  
  backgroundColor: `rgba(0, 0, 0, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  height: "100%",  
  width: "100%",  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Top: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `20px 0px 0px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
});
  
const Logo: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `16px 0px 0px 40px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const MoonbaseLogo: any = styled("img")({  
  height: `12px`,  
  width: `108px`,  
  objectFit: `cover`,  
  margin: `0px`,  
});
  
const MoonbaseLogoM: any = styled("img")({  
  height: `11px`,  
  width: `9px`,  
  objectFit: `cover`,  
  margin: `0px`,  
});
  
const List: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 0px 22px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `56px 0px 0px 0px`,  
});
  
const SidebarRow1: any = styled(SidebarRow)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `0px`,  
}));
  
const SidebarRow2: any = styled(SidebarRow)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `6px 0px 0px 0px`,  
}));
  
const SidebarRow3: any = styled(SidebarRow)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `6px 0px 0px 0px`,  
}));
  
const SidebarRow4: any = styled(SidebarRow)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `6px 0px 0px 0px`,  
}));
  
const SidebarRow5: any = styled(SidebarRow)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `6px 0px 0px 0px`,  
}));
  
const SidebarRow6: any = styled(SidebarRow)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `6px 0px 0px 0px`,  
}));
  
const SidebarRow7: any = styled(SidebarRow)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `6px 0px 0px 0px`,  
}));
  
const SidebarRow8: any = styled(SidebarRow)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `6px 0px 0px 0px`,  
}));
  
const Account1: any = styled("div")({  
  backgroundColor: `rgba(43, 43, 43, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `60px`,  
});
  
const AvatarRow: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px 30px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Avatar1: any = styled("img")({  
  height: `32px`,  
  width: `32px`,  
  objectFit: `cover`,  
  margin: `0px`,  
});
  
const FullName: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.64px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 8px`,  
});
 
function Sidebar(props: SidebarProps): JSX.Element {
  return (
    <CollapsableOpen className={props.className} >
      <Top >
        <Logo >
          <MoonbaseLogo  src={`assets/images/Sidebar_MoonbaseLogo.png`} alt={"MoonbaseLogo"}/>
          {false &&
            <MoonbaseLogoM  src={`assets/images/Sidebar_MoonbaseLogo_M.png`} alt={"MoonbaseLogo_M"}/>
          }
        </Logo>
        <List >
          <SidebarRow1   />
          <SidebarRow2   />
          <SidebarRow3   />
          <SidebarRow4   />
          <SidebarRow5   />
          <SidebarRow6   />
          <SidebarRow7   />
          <SidebarRow8   />
        </List>
      </Top>
      <Account1 >
        <AvatarRow >
          <Avatar1  src={`assets/images/Sidebar_Avatar.png`} alt={"Avatar"}/>
          <FullName >
            {`Ellen Cho`}
              </FullName>
        </AvatarRow>
      </Account1>
    </CollapsableOpen>
  );
}

export default Sidebar;
