/**********************************************************************
 *
 *   Types file generated by Quest
 *
 *   Types for the components props go in this file
 *   To set up custom types for the components props, edit the corresponding types in this file
 *   Once you edit a type to no longer by "any", be careful to not override it on your next export
 *   Verify diff before merging
 *
 *   For help and further details refer to:
 *   https://docs.quest.ai/react/fundamentals/exporting-code
 *
 *
 **********************************************************************/







export interface SwitchMonthlyAnnualProps {
  className?: any;
  isAnnual: any;
  onClick: any;
}







export interface PricingProps {
  className?: any;
}







export interface NavbarProps {
  className?: any;
}







export interface FooterProps {
  className?: any;
}







export interface FooterLinkProps {
  className?: any;
  text: any;
}







export interface FooterLink2Props {
  className?: any;
  text: any;
}







export interface HomeProps {
  className?: any;
}







export interface SoEasyDProps {
  className?: any;
}







export interface SoEasyTProps {
  className?: any;
}







export interface SoEasyMProps {
  className?: any;
}







export interface HowItWorksDProps {
  className?: any;
}







export interface HowItWorksTProps {
  className?: any;
}







export interface HowItWorksMProps {
  className?: any;
}


export interface ReactAppsProps {
  className?: any;
}


export interface ProductDropProps {
  className?: any;
}


export interface UseCasesDropProps {
  className?: any;
}


export interface VideoProps {
  className?: any;
}


export interface HtmlProps {
  className?: any;
}
