/**********************************************************************
*
*   Types file generated by Quest
*
*   Types for the components props go in this file
*   To set up custom types for the components props, edit the corresponding types in this file
*   Once you edit a type to no longer by "any", be careful to not override it on your next export 
*   Verify diff before merging
*
*   For help and further details refer to: 
*   https://docs.quest.ai/react/fundamentals/exporting-code
*
*
**********************************************************************/





export interface PaymentCardProps {
  className?: any;
};





export interface BreadcrumbsProps {
  className?: any;
};





export interface ProductCardProps {
  className?: any;
};





export interface NotificationsProps {
  className?: any;
};





export interface UpcomingProps {
  className?: any;
};





export interface DashboardProps {
  className?: any;
};





export interface NavBarProps {
  className?: any;
};





export interface ReactionProps {
  className?: any;
};





export interface SidebarProps {
  className?: any;
};





export interface FeedbackBarProps {
  className?: any;
};





export interface SidebarRowProps {
  className?: any;
};

