/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';

//These are the possible values for the current variant. Use this to change the currentVariant dynamically.
//Please don't modify
const variantOptions = {
  ScreenMobileStep1: 'ScreenMobileStep1',
  ScreenMobileStep2: 'ScreenMobileStep2',
  ScreenMobileStep3: 'ScreenMobileStep3',
  ScreenMobileStep4: 'ScreenMobileStep4',
};

const useHowItWorksM = () => {
  const [currentVariant, setCurrentVariant] = React.useState<string>(
    variantOptions['ScreenMobileStep1']
  );

  let data: any = { currentVariant };

  let fns: any = { setCurrentVariant };
  return { data, fns };
};

export default useHowItWorksM;
