/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import { HowItWorksTProps } from 'types';
import { animated, useSpring, easings } from 'react-spring';
import useHowItWorksT from 'components/HowItWorksT/useHowItWorksT';

const ScreenTabletStep1: any = styled('div')({
  backgroundColor: `rgba(23, 23, 23, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: 'auto',
});

const T: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Frame122: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `600px`,
  margin: `0px`,
});

const BarHighlight: any = animated(
  styled('div', {
    shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
  })(({ data }: any) => ({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    margin: `0px`,
    alignSelf:
      data.currentVariant === 'ScreenTabletStep3'
        ? `stretch`
        : data.currentVariant === 'ScreenTabletStep4'
        ? `stretch`
        : 'unset',
  }))
);

const Divider: any = styled('div')({
  backgroundColor: `rgba(46, 46, 46, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  alignSelf: `stretch`,
  height: `2px`,
  margin: `0px`,
});

const HighlightedBar: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Rectangle139: any = animated(
  styled('div', {
    shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
  })(({ data }: any) => ({
    backgroundColor: `rgba(254, 136, 136, 0)`,
    width: `1px`,
    height: `3px`,
    margin: `0px`,
  }))
);

const Rectangle141: any = animated(
  styled('div', {
    shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
  })(({ data }: any) => ({
    backgroundColor: `rgba(254, 136, 136, 1)`,
    width: `182px`,
    height: `3px`,
    margin: `0px`,
  }))
);

const TextLinks: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `flex-start`,
  padding: `0px 10px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `8px 0px 0px 0px`,
});

const SyncDs: any = animated(
  styled('div', {
    shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
  })(({ data }: any) => ({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    color: `rgba(254, 136, 136, 1)`,
    fontStyle: `normal`,
    fontFamily: `Visby CF`,
    fontWeight: `700`,
    fontSize: `13px`,
    letterSpacing: `0.30000001192092896px`,
    textDecoration: `none`,
    textTransform: `uppercase`,
  }))
);

const ExportDesign: any = animated(
  styled('div', {
    shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
  })(({ data }: any) => ({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    color: `rgba(255, 255, 255, 0.5)`,
    fontStyle: `normal`,
    fontFamily: `Visby CF`,
    fontWeight: `700`,
    fontSize: `13px`,
    letterSpacing: `0.30000001192092896px`,
    textDecoration: `none`,
    textTransform: `uppercase`,
  }))
);

const SetupInQuest: any = animated(
  styled('div', {
    shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
  })(({ data }: any) => ({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    color: `rgba(255, 255, 255, 0.5)`,
    fontStyle: `normal`,
    fontFamily: `Visby CF`,
    fontWeight: `700`,
    fontSize: `13px`,
    letterSpacing: `0.30000001192092896px`,
    textDecoration: `none`,
    textTransform: `uppercase`,
  }))
);

const ExportReact: any = animated(
  styled('div', {
    shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
  })(({ data }: any) => ({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    color: `rgba(255, 255, 255, 0.5)`,
    fontStyle: `normal`,
    fontFamily: `Visby CF`,
    fontWeight: `700`,
    fontSize: `13px`,
    letterSpacing: `0.30000001192092896px`,
    textDecoration: `none`,
    textTransform: `uppercase`,
  }))
);

const StepVisual1T: any = styled('img')({
  height: `315px`,
  width: `600px`,
  margin: `30px 0px 0px 0px`,
});

const StepVisual2T: any = styled('img')({
  height: `315px`,
  width: `600px`,
  margin: `30px 0px 0px 0px`,
});

const StepVisual3T: any = styled('img')({
  height: `315px`,
  width: `600px`,
  margin: `30px 0px 0px 0px`,
});

const StepVisual4T: any = styled('img')({
  height: `315px`,
  width: `600px`,
  margin: `30px 0px 0px 0px`,
});

function HowItWorksT(props: HowItWorksTProps): JSX.Element {
  const { data, fns } = useHowItWorksT();

  const BarHighlightScreenTabletStep1 = {};
  const BarHighlightScreenTabletStep2 = {};
  const BarHighlightScreenTabletStep3 = {};
  const BarHighlightScreenTabletStep4 = {};
  const [BarHighlightStateStyles, BarHighlightStateApi] = useSpring(() => ({
    from: eval('BarHighlight' + data.currentVariant),
    config: { duration: 1000 },
    delay: 500,
  }));

  const Rectangle139ScreenTabletStep1 = { width: `1px` };
  const Rectangle139ScreenTabletStep2 = { width: `196px` };
  const Rectangle139ScreenTabletStep3 = { width: `323px` };
  const Rectangle139ScreenTabletStep4 = { width: `453px` };
  const [Rectangle139StateStyles, Rectangle139StateApi] = useSpring(() => ({
    from: eval('Rectangle139' + data.currentVariant),
    config: { duration: 1000 },
    delay: 500,
  }));

  const Rectangle141ScreenTabletStep1 = { width: `182px` };
  const Rectangle141ScreenTabletStep2 = { width: `114px` };
  const Rectangle141ScreenTabletStep3 = { width: `113px` };
  const Rectangle141ScreenTabletStep4 = { width: `146px` };
  const [Rectangle141StateStyles, Rectangle141StateApi] = useSpring(() => ({
    from: eval('Rectangle141' + data.currentVariant),
    config: { duration: 1000 },
    delay: 500,
  }));

  const SyncDsScreenTabletStep1 = { color: `rgba(254, 136, 136, 1)` };
  const SyncDsScreenTabletStep2 = { color: `rgba(255, 255, 255, 0.5)` };
  const SyncDsScreenTabletStep3 = { color: `rgba(255, 255, 255, 0.5)` };
  const SyncDsScreenTabletStep4 = { color: `rgba(255, 255, 255, 0.5)` };
  const [SyncDsStateStyles, SyncDsStateApi] = useSpring(() => ({
    from: eval('SyncDs' + data.currentVariant),
    config: { duration: 1000 },
    delay: 500,
  }));

  const ExportDesignScreenTabletStep1 = { color: `rgba(255, 255, 255, 0.5)` };
  const ExportDesignScreenTabletStep2 = { color: `rgba(254, 136, 136, 1)` };
  const ExportDesignScreenTabletStep3 = { color: `rgba(255, 255, 255, 0.5)` };
  const ExportDesignScreenTabletStep4 = { color: `rgba(255, 255, 255, 0.5)` };
  const [ExportDesignStateStyles, ExportDesignStateApi] = useSpring(() => ({
    from: eval('ExportDesign' + data.currentVariant),
    config: { duration: 1000 },
    delay: 500,
  }));

  const SetupInQuestScreenTabletStep1 = { color: `rgba(255, 255, 255, 0.5)` };
  const SetupInQuestScreenTabletStep2 = { color: `rgba(255, 255, 255, 0.5)` };
  const SetupInQuestScreenTabletStep3 = { color: `rgba(254, 136, 136, 1)` };
  const SetupInQuestScreenTabletStep4 = { color: `rgba(255, 255, 255, 0.5)` };
  const [SetupInQuestStateStyles, SetupInQuestStateApi] = useSpring(() => ({
    from: eval('SetupInQuest' + data.currentVariant),
    config: { duration: 1000 },
    delay: 500,
  }));

  const ExportReactScreenTabletStep1 = { color: `rgba(255, 255, 255, 0.5)` };
  const ExportReactScreenTabletStep2 = { color: `rgba(255, 255, 255, 0.5)` };
  const ExportReactScreenTabletStep3 = { color: `rgba(255, 255, 255, 0.5)` };
  const ExportReactScreenTabletStep4 = { color: `rgba(254, 136, 136, 1)` };
  const [ExportReactStateStyles, ExportReactStateApi] = useSpring(() => ({
    from: eval('ExportReact' + data.currentVariant),
    config: { duration: 1000 },
    delay: 500,
  }));

  const switchStateToScreenTabletStep1: (
    duration: number,
    delay: number,
    easing: string
  ) => void = (
    duration: number = 0,
    delay: number = 0,
    easing: string = 'linear'
  ) => {
    BarHighlightStateApi.start({
      ...BarHighlightScreenTabletStep1,
      delay,
      config: { duration, easing: easings[easing] },
    });
    Rectangle139StateApi.start({
      ...Rectangle139ScreenTabletStep1,
      delay,
      config: { duration, easing: easings[easing] },
    });
    Rectangle141StateApi.start({
      ...Rectangle141ScreenTabletStep1,
      delay,
      config: { duration, easing: easings[easing] },
    });
    SyncDsStateApi.start({
      ...SyncDsScreenTabletStep1,
      delay,
      config: { duration, easing: easings[easing] },
    });
    ExportDesignStateApi.start({
      ...ExportDesignScreenTabletStep1,
      delay,
      config: { duration, easing: easings[easing] },
    });
    SetupInQuestStateApi.start({
      ...SetupInQuestScreenTabletStep1,
      delay,
      config: { duration, easing: easings[easing] },
    });
    ExportReactStateApi.start({
      ...ExportReactScreenTabletStep1,
      delay,
      config: { duration, easing: easings[easing] },
    });
  };

  const switchStateToScreenTabletStep2: (
    duration: number,
    delay: number,
    easing: string
  ) => void = (
    duration: number = 0,
    delay: number = 0,
    easing: string = 'linear'
  ) => {
    BarHighlightStateApi.start({
      ...BarHighlightScreenTabletStep2,
      delay,
      config: { duration, easing: easings[easing] },
    });
    Rectangle139StateApi.start({
      ...Rectangle139ScreenTabletStep2,
      delay,
      config: { duration, easing: easings[easing] },
    });
    Rectangle141StateApi.start({
      ...Rectangle141ScreenTabletStep2,
      delay,
      config: { duration, easing: easings[easing] },
    });
    SyncDsStateApi.start({
      ...SyncDsScreenTabletStep2,
      delay,
      config: { duration, easing: easings[easing] },
    });
    ExportDesignStateApi.start({
      ...ExportDesignScreenTabletStep2,
      delay,
      config: { duration, easing: easings[easing] },
    });
    SetupInQuestStateApi.start({
      ...SetupInQuestScreenTabletStep2,
      delay,
      config: { duration, easing: easings[easing] },
    });
    ExportReactStateApi.start({
      ...ExportReactScreenTabletStep2,
      delay,
      config: { duration, easing: easings[easing] },
    });
  };

  const switchStateToScreenTabletStep3: (
    duration: number,
    delay: number,
    easing: string
  ) => void = (
    duration: number = 0,
    delay: number = 0,
    easing: string = 'linear'
  ) => {
    BarHighlightStateApi.start({
      ...BarHighlightScreenTabletStep3,
      delay,
      config: { duration, easing: easings[easing] },
    });
    Rectangle139StateApi.start({
      ...Rectangle139ScreenTabletStep3,
      delay,
      config: { duration, easing: easings[easing] },
    });
    Rectangle141StateApi.start({
      ...Rectangle141ScreenTabletStep3,
      delay,
      config: { duration, easing: easings[easing] },
    });
    SyncDsStateApi.start({
      ...SyncDsScreenTabletStep3,
      delay,
      config: { duration, easing: easings[easing] },
    });
    ExportDesignStateApi.start({
      ...ExportDesignScreenTabletStep3,
      delay,
      config: { duration, easing: easings[easing] },
    });
    SetupInQuestStateApi.start({
      ...SetupInQuestScreenTabletStep3,
      delay,
      config: { duration, easing: easings[easing] },
    });
    ExportReactStateApi.start({
      ...ExportReactScreenTabletStep3,
      delay,
      config: { duration, easing: easings[easing] },
    });
  };

  const switchStateToScreenTabletStep4: (
    duration: number,
    delay: number,
    easing: string
  ) => void = (
    duration: number = 0,
    delay: number = 0,
    easing: string = 'linear'
  ) => {
    BarHighlightStateApi.start({
      ...BarHighlightScreenTabletStep4,
      delay,
      config: { duration, easing: easings[easing] },
    });
    Rectangle139StateApi.start({
      ...Rectangle139ScreenTabletStep4,
      delay,
      config: { duration, easing: easings[easing] },
    });
    Rectangle141StateApi.start({
      ...Rectangle141ScreenTabletStep4,
      delay,
      config: { duration, easing: easings[easing] },
    });
    SyncDsStateApi.start({
      ...SyncDsScreenTabletStep4,
      delay,
      config: { duration, easing: easings[easing] },
    });
    ExportDesignStateApi.start({
      ...ExportDesignScreenTabletStep4,
      delay,
      config: { duration, easing: easings[easing] },
    });
    SetupInQuestStateApi.start({
      ...SetupInQuestScreenTabletStep4,
      delay,
      config: { duration, easing: easings[easing] },
    });
    ExportReactStateApi.start({
      ...ExportReactScreenTabletStep4,
      delay,
      config: { duration, easing: easings[easing] },
    });
  };
  return (
    <ScreenTabletStep1>
      <T>
        <Frame122>
          <BarHighlight data={data} style={{ ...BarHighlightStateStyles }}>
            <Divider></Divider>
            <HighlightedBar>
              <Rectangle139
                data={data}
                style={{ ...Rectangle139StateStyles }}
              ></Rectangle139>
              <Rectangle141
                data={data}
                style={{ ...Rectangle141StateStyles }}
              ></Rectangle141>
            </HighlightedBar>
          </BarHighlight>
          <TextLinks>
            <SyncDs
              data={data}
              onClick={() => {
                switchStateToScreenTabletStep1(500, 0, 'easeOutQuart');
                fns.setCurrentVariant('ScreenTabletStep1');
              }}
              style={{ ...SyncDsStateStyles }}
            >
              {`Sync MUI Design System`}
            </SyncDs>
            <ExportDesign
              data={data}
              onClick={() => {
                switchStateToScreenTabletStep2(500, 0, 'easeOutQuart');
                fns.setCurrentVariant('ScreenTabletStep2');
              }}
              style={{ ...ExportDesignStateStyles }}
            >
              {`EXPORT DESIGN`}
            </ExportDesign>
            <SetupInQuest
              data={data}
              onClick={() => {
                switchStateToScreenTabletStep3(500, 0, 'easeOutQuart');
                fns.setCurrentVariant('ScreenTabletStep3');
              }}
              style={{ ...SetupInQuestStateStyles }}
            >
              {`SETUP IN QUEST`}
            </SetupInQuest>
            <ExportReact
              data={data}
              onClick={() => {
                switchStateToScreenTabletStep4(500, 0, 'easeOutQuart');
                fns.setCurrentVariant('ScreenTabletStep4');
              }}
              style={{ ...ExportReactStateStyles }}
            >
              {`EXPORT REACT CODE`}
            </ExportReact>
          </TextLinks>
        </Frame122>
        {!(data.currentVariant === 'ScreenTabletStep2') &&
          !(data.currentVariant === 'ScreenTabletStep3') &&
          !(data.currentVariant === 'ScreenTabletStep4') && (
            <StepVisual1T
              src={`assets/images/HowitworksT_Step_Visual_1__T.png`}
              loading="lazy"
              alt={'Step Visual 1 -T'}
            />
          )}
        {data.currentVariant === 'ScreenTabletStep2' && (
          <StepVisual2T
            src={`assets/images/HowitworksT_Step_Visual_2___T.png`}
            loading="lazy"
            alt={'Step Visual 2 - T'}
          />
        )}
        {data.currentVariant === 'ScreenTabletStep3' && (
          <StepVisual3T
            src={`assets/images/HowitworksT_Step_Visual_3___T.png`}
            loading="lazy"
            alt={'Step Visual 3 - T'}
          />
        )}
        {data.currentVariant === 'ScreenTabletStep4' && (
          <StepVisual4T
            src={`assets/images/HowitworksT_Step_Visual_4___T.png`}
            loading="lazy"
            alt={'Step Visual 4 - T'}
          />
        )}
      </T>
    </ScreenTabletStep1>
  );
}

export default HowItWorksT;
