/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';

//These are the possible values for the current variant. Use this to change the currentVariant dynamically.
//Please don't modify
const variantOptions = {
  ScreenTabletStep1: 'ScreenTabletStep1',
  ScreenTabletStep2: 'ScreenTabletStep2',
  ScreenTabletStep3: 'ScreenTabletStep3',
  ScreenTabletStep4: 'ScreenTabletStep4',
};

const useHowItWorksT = () => {
  const [currentVariant, setCurrentVariant] = React.useState<string>(
    variantOptions['ScreenTabletStep1']
  );

  let data: any = { currentVariant };

  let fns: any = { setCurrentVariant };
  return { data, fns };
};

export default useHowItWorksT;
