/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import { SwitchMonthlyAnnualProps } from 'types';

const BillingCycleAnnual: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: 'auto',
  width: 'fit-content',
  cursor: `pointer`,
});

const SwitchComponent: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Monthly: any = styled('div', {
  shouldForwardProp: (prop: any) => !['props'].includes(prop.toString()),
})(({ props }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: !props.isAnnual ? `rgba(255, 255, 255, 1)` : `rgba(127, 127, 127, 1)`,
  fontStyle: `normal`,
  fontFamily: `Visby CF`,
  fontWeight: `700`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `70px`,
  height: `29px`,
  margin: `0px`,
}));

const SwitchMonthly: any = styled('img')({
  height: `38px`,
  width: `58px`,
  margin: `0px 0px 0px 2px`,
});

const SwitchAnnual: any = styled('img')({
  height: `38px`,
  width: `58px`,
  margin: `0px 0px 0px 2px`,
});

const Annual: any = styled('div', {
  shouldForwardProp: (prop: any) => !['props'].includes(prop.toString()),
})(({ theme, props }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: !props.isAnnual ? `rgba(127, 127, 127, 1)` : `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Visby CF`,
  fontWeight: `700`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `62px`,
  height: `29px`,
  margin: `0px 0px 0px 2px`,
}));

function SwitchMonthlyAnnual(props: SwitchMonthlyAnnualProps): JSX.Element {
  return (
    <BillingCycleAnnual onClick={props.onClick}>
      <SwitchComponent>
        <Monthly props={props}>{`Monthly`}</Monthly>
        {!props.isAnnual && (
          <SwitchMonthly
            src={`assets/images/SwitchMonthlyAnnual_switch_monthly.png`}
            loading="lazy"
            alt={'switch_monthly'}
          />
        )}
        {!!props.isAnnual && (
          <SwitchAnnual
            src={`assets/images/SwitchMonthlyAnnual_switch_annual.png`}
            loading="lazy"
            alt={'switch_annual'}
          />
        )}
        <Annual props={props}>{`Annual`}</Annual>
      </SwitchComponent>
    </BillingCycleAnnual>
  );
}

export default SwitchMonthlyAnnual;
