/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import Avatar1Image from 'src/assets/images/NavBar_Avatar.png';
import { styled } from '@mui/material/styles';
import { NavBarProps } from 'src/types';

 
const NavBar1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  height: `80px`,  
  width: `1133px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Content: any = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-end`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `80px`,  
  margin: `0px`,  
});
  
const RightSide2: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-end`,  
  alignItems: `flex-end`,  
  padding: `0px 28px 0px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const Account: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-end`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const Avatar1: any = styled("img")({  
  height: `40px`,  
  width: `40px`,  
  objectFit: `cover`,  
  margin: `0px`,  
});
  
const EllenCho: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.64px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  width: `127px`,  
  height: `25.83px`,  
  margin: `0px 0px 0px 18px`,  
});
 
function NavBar(props: NavBarProps): JSX.Element {
  return (
    <NavBar1 className={props.className} >
      <Content >
        <RightSide2 >
          <Account >
            <Avatar1  src={Avatar1Image} alt={"Avatar"}/>
            <EllenCho >
              {`Ellen Cho`}
                </EllenCho>
          </Account>
        </RightSide2>
      </Content>
    </NavBar1>
  );
}

export default NavBar;
