/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import useContactResponsiveSize from './useContactResponsiveSize';

//These are the possible values for the current variant. Use this to change the currentVariant dynamically.
//Please don't modify
const variantOptions = {
  Property1ContactDesktop: 'Property1ContactDesktop',
  Property1ContactTablet: 'Property1ContactTablet',
  Property1ContactMobile: 'Property1ContactMobile',
};

const useContact = () => {
  const [currentVariant, setCurrentVariant] = React.useState<string>(
    variantOptions['Property1ContactDesktop']
  );

  const breakpointsVariant = useContactResponsiveSize();

  React.useEffect(() => {
    if (breakpointsVariant !== currentVariant) {
      setCurrentVariant(breakpointsVariant);
    }
  }, [breakpointsVariant]);

  let data: any = { currentVariant };

  let fns: any = { setCurrentVariant };
  return { data, fns };
};

export default useContact;
