/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Link } from '@mui/material';
import { styled } from '@mui/material/styles';
import { UseCasesDropProps } from 'types';

const Property1Default: any = styled('div')({
  backgroundColor: `rgba(23, 23, 23, 1)`,
  border: `1px solid rgba(73, 73, 73, 1)`,
  boxSizing: `border-box`,
  borderRadius: `6px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `30px`,
  height: 'auto',
});

const ForStartups: any = styled(Link)({
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Visby CF`,
  fontWeight: `700`,
  fontSize: `18px`,
  letterSpacing: `0.5px`,
  lineHeight: `21px`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const ForAgencies: any = styled(Link)({
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Visby CF`,
  fontWeight: `700`,
  fontSize: `18px`,
  letterSpacing: `0.5px`,
  lineHeight: `21px`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `20px 0px 0px 0px`,
});

const ForWeb3: any = styled(Link)({
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Visby CF`,
  fontWeight: `700`,
  fontSize: `18px`,
  letterSpacing: `0.5px`,
  lineHeight: `21px`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `20px 0px 0px 0px`,
});

function UseCasesDrop(props: UseCasesDropProps): JSX.Element {
  return (
    <Property1Default>
      <ForStartups href="#" underline="hover">
        For Startups
      </ForStartups>
      <ForAgencies href="#" underline="hover">
        For Agencies
      </ForAgencies>
      <ForWeb3 href="#" underline="hover">
        For Web3
      </ForWeb3>
    </Property1Default>
  );
}

export default UseCasesDrop;
