/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { SvgIcon } from '@mui/material';
import { ReactComponent as Home1 } from 'assets/images/Home_2.svg';
import { styled } from '@mui/material/styles';
import { SidebarRowProps } from 'types';

 
const Property1Default: any = styled("div")({  
  backgroundColor: `rgba(0, 0, 0, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: `40px`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px 32px 0px 12px`,  
  boxSizing: `border-box`,  
});
  
const Icon1: any = styled(SvgIcon)(({ theme }: any) =>({  
  color: theme.palette["Primary"]["Contrast"],  
  margin: `0px`,  
}));
  
const Text: any = styled("div")(({ theme }: any) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: theme.palette["Primary"]["Contrast"],  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.64px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 13px`,  
}));
 
function SidebarRow(props: SidebarRowProps): JSX.Element {
  return (
    <Property1Default className={props.className} >
      <Icon1    fontSize = { "medium"}  component = { Home1}/>
      <Text >
        {`Dashboard`}
          </Text>
    </Property1Default>
  );
}

export default SidebarRow;
